bashMapping = {
    'slash': 'slash',
    'backslash': 'backslash',
    'backspace': 'backspace',
    'bash buck': 'c-e',
    'bash paste': 'c-y',
    'cancel': 'c-c',
    'caret': 'caret',
    'carrot': 'caret',
    'delete': 'delete',
    'hyphen': 'hyphen',
    'left': 'left',
    'left word': 'a-b',
    'pipe': 'bar',
    'pipe space': 'space,bar,space',
    'up': 'up',
    'down': 'down', 
    'right': 'right',
    'right word': 'a-f',
    'scratch head': 'c-u',
    'scratch tail': 'c-k',
} 
