# character mappings

charMapping = {
        'alpha':"a",
        'bravo':"b",
        'charlie': "c",
        'delta':   "d",
        'eli': "e",
        'foxtrot': "f",
        'george': "g",
        'hank': "h",
        'ike': "i",
        'jake': "j", 
        'kilo': "k", 
        'lima': "l", 
        'mike': "m", 
        'noah': "n",
        'oscar': "o",
        'papa': "p",
        'quentin': "q",
        'quintin': "q",
        'randy': "r",
        'simon': "s",
        'tango': "t",
        'udall': "u",
        'victor': "v",
        'whiskey': "w",
        'x-ray':"x",
        'yankee': "y",
        'zulu': "z",
        # uppercase characters
        'stout alpha': 'A',
        'stout bravo':"B",
        'stout charlie': "C",
        'stout delta':   "D",
        'stout eli': "E",
        'stout foxtrot': "F",
        'stout george': "G",
        'stout hank': "H",
        'stout ike': "I",
        'stout jake': "J", 
        'stout kilo': "K", 
        'stout lima': "L", 
        'stout mike': "M", 
        'stout noah': "N",
        'stout oscar': "O",
        'stout papa': "P",
        'stout quentin': "Q",
        'stout quintin': "Q",
        'stout randy': "R",
        'stout simon': "S",
        'stout tango': "T",
        'stout udall': "U",
        'stout victor': "V",
        'stout whiskey': "W",
        'stout x-ray':"X",
        'stout yankee': "Y",
        'stout zulu': "Z"

    }
