programming_mapping = {
        "amp": "ampersand",
        "amp twice": "ampersand,ampersand",
        "arc": "lparen",
        "arc end": "rparen",
        "arc and": "rparen",

        "bang": "exclamation",
        "Christ": "plus",
        "Christ space": "space,plus,space",
        "Christ twice": "space,plus,space",
        ",": "comma",
        'snake': 'underscore',
        "crimp": "lbrace",
        "crimp end": "rbrace",
        "crypt": "question",
        "dot": "dot",
        "hash": "hash",
        "minus": "minus",
        "mod": "percent",
        "optic": "colon",
        'optic twice': 'colon,colon',
        'pipe twice':'space,bar,space,bar,left,backspace,right,space',

        "raft": "lbracket",
        "raft and": "rbracket",
        "raft end": "rbracket",
        "sever": "semicolon",
        "slug": "asterisk",
        "tick": "squote",
        "tick twice": "dquote",
        "trout": "rangle",
        "trout less": "langle",
        "way Stowe": "space,equal,equal,space",
        "way stow": "space,equal,equal,space",
        "way Stowe strict": "space,equal,equal,equal,space",
        "way Stow strict": "space,equal,equal,equal,space",
        'whale': 'space,equal,rangle,space',
} 
