# vocabulary mappings for vim 
vimMapping = {
        "arc": "lparen",
        "arc end": "rparen",
        "bag": "v",
        "bag block": "c-v",
        "boost": "k",
        "buck": "dollar",
        "cleave": "o",
        "cleve": "o",
        "cleave up": "O",
        "cleve up": "O",
        "crimp": "lbrace",
        "crimp end": "rbrace",
        "dub": "w",
        "etch": "i",
        "etch start": "I",
        "hind": "b",
        "hynde": "b",
        "indent": "equal,equal",
        "lance":"a",
        "lance tip":"A",
        "leaf bottom": "G",
        "leaf top": "g,g",
        "lop": "d",
        "lop line": "d,d",
        "nib": "e",
        "oust": "c",
        "page down": "pgdown",
        "page up": "pgup",
        "paste": "p",
        "paste front": "P",
        "raft": "lbracket",
        "raft end": "rbracket",
        "scape": "escape",
        "shoot": "enter",
        "slump": "j",
        "swap": "r",
        "swap more": "R",
        "sub": "s",
        "sub line": "S",
        "tick": "squote",
        "tick twice": "dquote",
        "trim": "x",
        "trim back": "X",
        "trout": "rangle",
        "trout less": "langle",
        "yank": "y",
        "zilch": "0",
}


